version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    container_name: zenblog-jekyll
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --force_polling --livereload --host 0.0.0.0
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    stdin_open: true
    tty: true
